[[agents]]
id = "liza_id"
name = "Li-za"
public_address = "HcScJ77H3rsOgEjebtoXZ8oU4UCgjndk9fTvkVt77C84CnnwcJ3OMfg5K8m7dga"
keystore_file = "/home/lisa/.config/holochain/keys/HcScJ77H3rsOgEjebtoXZ8oU4UCgjndk9fTvkVt77C84CnnwcJ3OMfg5K8m7dga"

# DNA and Instance of the HApp Store
[[dnas]]
id = "happ_store_dna"
file = "dna/HAppStore/dist/HAppStore.dna.json"
hash = "Qm328wyq38924x"

[[instances]]
id = "happ-store"
dna = "happ_store_dna"
agent = "liza_id"
[instances.logger]
type = "simple"
file = "app_spec2.log"
[instances.storage]
type = "file"
path = "tmp-storage-1"

# DNA and Instance of the HoloHostingApp
[[dnas]]
id = "hha_dna"
file = "dna/HoloHostingApp/dist/HoloHostingApp.dna.json"
hash = "QmSqPoNS5n1GnaBmJXq42RK3FdZaAKnid1ueBnMbuyJYCD"

[[instances]]
id = "holo-hosting-app"
dna = "hha_dna"
agent = "liza_id"
[instances.logger]
type = "simple"
file = "app_spec.log"
[instances.storage]
type = "file"
path = "tmp-storage-2"

[[interfaces]]
id = "websocket_interface"
[interfaces.driver]
type = "websocket"
port = 1111
[[interfaces.instances]]
id = "holo-hosting-app"
[[interfaces.instances]]
id = "happ-store"

[[ui_bundles]]
id = "main"
root_dir = "./ui"
hash = "Qm000"

[[ui_interfaces]]
id = "ui-interface"
bundle = "main"
port = 8800
dna_interface = "websocket_interface"

[[ui_bundles]]
id = "happ_store_main"
root_dir = "/home/zo-el/Documents/GitRepo/Holochain/holo-hosting/HApps-Store/ui-happ-store"
hash = "Qm000"

[[ui_interfaces]]
id = "happ-store-ui-interface"
bundle = "happ_store_main"
port = 8000
dna_interface = "websocket_interface"
